export const DELETE_LOC_REQUEST = "DELETE_LOC_REQUEST";
export const DELETE_LOC_SUCCESS = "DELETE_LOC_SUCCESS";
export const DELETE_LOC_FAIL = "DELETE_LOC_FAIL";

export const NEW_LOC_REQUEST = "NEW_LOC_REQUEST";
export const NEW_LOC_SUCCESS = "NEW_LOC_SUCCESS";
export const NEW_LOC_FAIL = "NEW_LOC_FAIL";

export const UPDATE_LOC_REQUEST = "UPDATE_LOC_REQUEST";
export const UPDATE_LOC_SUCCESS = "UPDATE_LOC_SUCCESS";
export const UPDATE_LOC_FAIL = "UPDATE_LOC_FAIL";