export const All_QUERY_REQUEST = "All_QUERY_REQUEST";
export const All_QUERY_SUCCESS = "All_QUERY_SUCCESS";
export const All_QUERY_FAIL = "All_QUERY_FAIL";

export const NEW_QUERY_REQUEST = "NEW_QUERY_REQUEST";
export const NEW_QUERY_SUCCESS = "NEW_QUERY_SUCCESS";
export const NEW_QUERY_FAIL = "NEW_QUERY_FAIL";

export const CLEAR_RESPONSE = "CLEAR_RESPONSE";


export const STATUS_REQUEST = "STATUS_REQUEST";
export const STATUS_SUCCESS = "STATUS_SUCCESS";
export const STATUS_FAIL = "STATUS_FAIL";